### ISSUE TITLE
create-hid.sh: line 34: echo: write error: No such device

### ISSUE THREAD

**Issue by sscirrus** [ppolstra/UDeck#1]
I'm playing around with create-hid for BBB and I'm running into this error:

`debian@beaglebone:~$ sudo bash create-hid.sh` 
`[sudo] password for debian:`
`create-hid.sh: line 34: echo: write error: No such device`

What's happening here? Line 34 is the last line and it refers to some file called 'musb-hdrc.0.auto', which isn't in the repo.

Am I supposed to copy the repo to a specific folder in the BBB before running it?

**Comment by sscirrus** [comment]
After doing some digging, I find the following matches for "musb-hdrc*" on the BBB Wireless:

/sys/kernel/debug/musb-hdrc.1
/sys/kernel/debug/musb-hdrc.1.dsps
/sys/kernel/debug/musb-hdrc.0
/sys/kernel/debug/musb-hdrc.0.dsps
/sys/devices/platform/ocp/47400000.usb/47401400.usb/musb-hdrc.0
/sys/devices/platform/ocp/47400000.usb/47401400.usb/musb-hdrc.0/udc/musb-hdrc.0
/sys/devices/platform/ocp/47400000.usb/47401c00.usb/musb-hdrc.1
/sys/class/udc/musb-hdrc.0
/sys/bus/platform/devices/musb-hdrc.1
/sys/bus/platform/devices/musb-hdrc.0
/sys/bus/platform/drivers/musb-hdrc
/sys/bus/platform/drivers/musb-hdrc/musb-hdrc.1
/sys/bus/platform/drivers/musb-hdrc/musb-hdrc.0
/proc/irq/202/musb-hdrc.0
/proc/irq/203/musb-hdrc.1

None of these are exact matches for `musb-hdrc.0.auto`. I don't know where this file is that the script seems to need.

**Comment by ppolstra** [comment]
What version of Debian are you running?  What is the kernel version.  It
needs to be a 4.x kernel for the HID functionality to work.  If you are
using the most recent version of Debian something might have changed from
the time I created the UDeck.

**Comment by sscirrus** [comment]
I'm running Debian GNU/Linux 9 (stretch), the latest image of Debian for BBB Wireless.
uname -r returns: 4.9.45-ti-r57.

I would hugely appreciate your help - I bought a BBB Wireless just for this!

**Comment by ppolstra** [comment]
This was originally release to work with Ubuntu 14.04.  At the time it was
released Debian was still on a 3.x kernel which does not support HID
devices.  If you load Ubuntu 14.04 on the BBB this should work fine without
modification.

**Comment by sscirrus** [comment]
It seems that Beaglebone has moved in the direction of Debian: see [latest images](http://beagleboard.org/latest-images).

The one I'm running now has a 4.x kernel (4.9) so it should be able to support HID devices. Is there a way to easily tweak the script so it'll work with current BBs? It works all the way up to the last line (line 34).

If not, I'll try a newer version of Ubuntu tomorrow and see if that works.
