### ISSUE TITLE
running ./create-hid.sh returns Device or resource busy

### ISSUE THREAD

**Issue by andyforeverest** [ppolstra/UDeck#2]
Hello Sir,

I would like to use a Beaglebone Black to emulate a keyboard that will be connected to a PC via USB.

I found your DEF CON presentation online and it was very good! It gave me a handle on how to approach this problem.

My BBB runs **Linux beaglebone 4.14.49-ti-r54**. 

When I run create-hid.sh I get these errors:

./create-hid.sh: line 29: echo: write error: Device or resource busy
./create-hid.sh: line 30: echo: write error: Device or resource busy
./create-hid.sh: line 31: echo: write error: Device or resource busy
cp: error writing '/sys/kernel/config/usb_gadget/kb/functions/hid.usb0/report_desc': Device or resource busy
ln: failed to create symbolic link '/sys/kernel/config/usb_gadget/kb/configs/c.1/hid.usb0': File exists
./create-hid.sh: line 34: echo: write error: No such device

Could you please help me solve this issue?

Thank you!

**Comment by ppolstra** [comment]
Are you running this script as root?  If not, it would explain this error.

**Comment by ppolstra** [comment]
It also could be an issue if you are running Debian.  The scripts were designed to run with Ubuntu.

**Comment by andyforeverest** [comment]
Yes, I am running as root.
